services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-portal_sanroque}_web
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - "${PORT:-8080}:80"
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  internal:
    driver: bridge
